<!DOCTYPE html><html class="no-js" lang="en"><head><?= $scripts ?><script>fbq('track', 'AddToCart');</script></head><body><?= isset($header) ? $header : "" ?>
<?= isset($header_form) ? $header_form : "" ?><section class="page-wrapper mt-50" id="page-content"><!-- SHOP SECTION START--><div class="shop-section mb-80"><div class="container"><h2><?= $text_new_order_detail; ?></h2><!--ul.cart-tab.row.mb-80--><!--    li.col-lg-4.col-md-4.col-sm-4.col-xs-4--><!--        a.active(href='#' onclick='return false;', style='cursor: default;')--><!--            span 1--><!--            | <?= $breadcrumbs_step_1; ?>--><!--    li.col-lg-4.col-md-4.col-sm-4.col-xs-4--><!--        a.active(href='#', onclick='return false;', style='cursor: default;')--><!--            span 2--><!--            | <?= $breadcrumbs_step_2; ?>--><!--    li.col-lg-4.col-md-4.col-sm-4.col-xs-4--><!--        a(href='#', onclick='return false;', style='cursor: default;')--><!--            span 3--><!--            | <?= $breadcrumbs_step_3; ?>--><? foreach($products as $product): ?>
<? if($flash): ?><div class="row"><div class="alert alert-danger"><?= $flash['content']; ?></div></div><? endif; ?><div class="row"><div class="col-md-5 col-sm-12 col-xs-12"><div class="row"><div class="col-md-12"><p class="mb-0"> <b><?= $details_order; ?><u><?= $product['name']; ?></u></b></p><p class="mb-0"><?= $details_imei; ?> <?= $product['imei']; ?></p><p class="mb-0"><?= $details_carrier; ?> <?= $product['carrier']; ?></p></div></div><div class="row mt-10"><div class="col-md-4 col-sm-4"><img src="<?= $product['thumb']; ?>" alt=""></div><div class="col-md-8 col-sm-8"><h2 class="label label-success p-10"><i class="zmdi zmdi-time-countdown mr-5"></i><?= $details_delivery_time; ?> <?= $product['delivery_time']; ?></h2><p class="mt-10 mb-0"><?= $details_competitors_price; ?> <?= $product['competitors_price']; ?></p><p class="mb-0"><?= $details_save_price; ?> <?= $product['save']; ?></p><p class="mb-0"><?= $details_our_price; ?> <b>US$<?= $product['total']; ?></b></p><p class="mt-10"><a class="text-danger" href="<?= $product['remove']; ?>"><?= $details_remove; ?></a></p></div></div></div><div class="col-md-7 col-sm-12 col-xs-12" id="product-description" style="color: #434343"><p class="hidden-lg hidden-md"><?= $product['description']; ?></p></div></div><div class="row"><div class="col-md-12"><hr></div></div><? endforeach; ?><!-- .row.row-equal-height.mt-50.col-lg-4.col-md-4.col-sm-12.col-xs-12.text-center
    .well
        h1 <?= $hero_box_1_header; ?>
        p <?= $hero_box_1_content; ?>
.col-lg-4.col-md-4.col-sm-12.col-xs-12.text-center
    .well
        h1 <?= $hero_box_2_header; ?>
        p <?= $hero_box_2_content; ?>
.col-lg-4.col-md-4.col-sm-12.col-xs-12.text-center
    .well
        h1 <?= $hero_box_3_header; ?>
        p <?= $hero_box_3_content; ?>--><div class="row mt-50"><div class="col-md-8"><div class="box-shadow p-30" id="risk-free-policy"><h2 class="widget-title border-left mb-20"><?= $risk_free_header; ?></h2><p> <strong><?= $risk_free_subheader; ?></strong></p><ul><li><?= $risk_free_list_1; ?></li><li><?= $risk_free_list_2; ?></li><li><?= $risk_free_list_3; ?></li><li><?= $risk_free_list_4; ?></li><li><?= $risk_free_list_5; ?></li><li><?= $risk_free_list_6; ?></li><li><?= $risk_free_list_7; ?></li><li><?= $risk_free_list_8; ?></li></ul></div></div><div class="col-md-4"><div class="row"><div class="col-md-12"><div class="coupon-discount box-shadow p-30 mb-20"><h6 class="widget-title border-left mb-20"><?= $coupon_header; ?></h6><p><?= $coupon_description; ?></p><p class="text-danger" id="coupon-error"></p><input id="coupon" type="text" name="name" placeholder="<?= $coupon_placeholder; ?>."><button class="submit-btn-1 black-bg btn-hover-2" id="button-coupon" type="submit"><?= $coupon_button; ?></button></div></div></div><div class="row"><div class="col-md-12"><div class="row"><div class="col-md-12"><div class="payment-details box-shadow p-30 mb-20"><h6 class="widget-title border-left mb-20"><?= $payment_header; ?></h6><table><tbody><? foreach($totals as $total): ?><tr><td class="td-title-1"><?= $total['title']; ?></td><td class="td-title-2"><?= $total['text']; ?></td></tr></tbody><? endforeach; ?></table><!-- shopping-cart end--><div class="row"><div class="col-md-12"><!-- Modal--><div class="modal fade" id="terms-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"><div class="modal-dialog" role="document"><div class="modal-content p-20"><p>Loading..</p></div></div></div><div class="checkbox"><label><input class="mt-5" id="terms-agree" type="checkbox"><?= $text_agree ?> <a style="text-decoration: underline" href="index.php?route=information/information/info&amp;information_id=5" data-toggle="modal" data-target="#terms-modal"><?= $text_terms ?></a></label></div></div></div><div class="row text-center" id="loading" style="display:none;"><p> <i class="zmdi zmdi-spinner spin mr-10"> </i>Loading, please wait..</p></div><div class="row text-center"><div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-center"><?= $stripe_new ?></div><!-- .col-lg-12.col-md-12.col-sm-12.col-xs-12.text-center.mt-5p.mt-0.mb-0 or--><!-- .col-lg-12.col-md-12.col-sm-12.col-xs-12.text-center.mt-5| <?= $paypal_express_new ?>
--></div></div></div></div></div></div></div></div></div></div><!-- SHOP SECTION END--><?= $footer ?>  </section></body></html>